# ESM模型参数
ESM_MODEL_NAME = "facebook/esm2_t30_150M_UR50D"
ESM_OUTPUT_DIR = "results/models/esm_finetuned"
ESM_FINETUNE_EPOCHS = 6
ESM_BATCH_SIZE = 16
ESM_LEARNING_RATE = 1e-5

# VAE模型参数
LATENT_DIM = 50
HIDDEN_DIM = 256
VAE_BATCH_SIZE = 32
VAE_LEARNING_RATE = 0.001
VAE_EPOCHS = 100
KL_WEIGHT = 0.1  # KL散度的权重

# 生成参数
NUM_SAMPLES = 10 